feat: configure sonarqube for code coverage analysis
hei-school/poja pull request #49
Opened 2024-03-11 13:14 UTC by NyH1409

2024-03-12 10:06 UTC, Dinasoa requested changes

2024-03-12 10:06 UTC, Dinasoa commented on .github/workflows/ci-with-sonar.yml
Dont create a new file to include sonar in your CI. Just put a placeholder then add the steps in poja-cli if with-sonar is true

2024-03-12 13:31 UTC, Onitsiky commented on .github/workflows/ci.yml
This change should not event appear here

2024-03-12 13:34 UTC, Onitsiky commented on build.gradle
> +
Change using <?sonarqube-java-plugin> for example

2024-03-12 13:35 UTC, Onitsiky commented on build.gradle
> +sonarqube {
This should only be added when with_sonar is set to true. 
Better to set it in poja-cli and just leave a placeholder here (<?sonarqube-conf> for example)

2024-03-13 05:44 UTC, Onitsiky commented on .github/workflows/ci.yml
> +      - name: Cache SonarCloud packages
Ibid here

2024-03-15 10:58 UTC, Onitsiky approved these changes

2024-03-15 11:20 UTC, merged